In [15]:
import numpy as np
import pandas as pd

In [16]:
#Head is used to print the rows presents in the data frame
books = pd.read_csv('Books.csv')
books.head()

C:\Users\YES !M\AppData\Local\Temp\ipykernel_11300\2273988395.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [17]:
#Shape is used to print the total no. of entries present in data frame
print("No.of Books : ",books.shape)
print()
print("Attributes Having null values ")
print(books.isnull().sum())
print()
print("No. of Duplicated Books :",books.duplicated().sum())

No.of Books :  (271360, 8)

Attributes Having null values
ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

No. of Duplicated Books : 0

In [18]:
users = pd.read_csv('Users.csv')
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [19]:
print("No.of Users : ",users.shape)
print()
print("Attributes Having null values ")
print(users.isnull().sum())
print()
print("No. of Duplicated Users :",users.duplicated().sum())

No.of Users :  (278858, 3)

Attributes Having null values
User-ID          0
Location         0
Age         110762
dtype: int64

No. of Duplicated Users : 0

In [20]:
ratings = pd.read_csv('Ratings.csv')
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [21]:
print("No.of Ratings : ",ratings.shape)
print()
print("Attributes Having null values ")
print(ratings.isnull().sum())
print()
print("No. of Duplicated Ratings :",ratings.duplicated().sum())

No.of Ratings :  (1149780, 3)

Attributes Having null values
User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

No. of Duplicated Ratings : 0

## Popularity based recommendation system
## Based on Top 50 Books with highest average rating of 250

In [22]:
#'inplace=True' if we want to commit the changes to the dataframe
ratings_with_bookname = ratings.merge(books,on='ISBN')
num_rating = ratings_with_bookname.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating.rename(columns={'Book-Rating':'Num-Ratings'},inplace=True)
num_rating

                                               Book-Title  Num-Ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [23]:
avg_rating = ratings_with_bookname.groupby('Book-Title')['Book-Rating'].agg('mean').reset_index()
avg_rating.rename(columns={'Book-Rating':'Avg-Ratings'}, inplace=True)
avg_rating

                                               Book-Title  Avg-Ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [24]:
popular = num_rating.merge(avg_rating,on='Book-Title')
popular

,Book-Title,Num-Ratings,Avg-Ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [25]:
#Top 50 books having rating of more than 250
popular=popular[popular['Num-Ratings']>=250].sort_values('Avg-Ratings',ascending=False).head(50)
popular=popular.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Year-Of-Publication','Image-URL-M','Num-Ratings','Avg-Ratings']]
popular

,Book-Title,Book-Author,Year-Of-Publication,Image-URL-M,Num-Ratings,Avg-Ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2000,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,1998,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,2000,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,1986,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,1986,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,1986,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,1988,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,Dan Brown,2003,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,2003,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,1991,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,2002,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,1990,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,2001,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,Neil Gaiman,1998,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,2003,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,2002,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,1997,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,1998,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,1982,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,2002,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
100,Into the Wild,Jon Krakauer,1997,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
103,Fahrenheit 451,Ray Bradbury,1994,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
116,Girl with a Pearl Earring,Tracy Chevalier,2001,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
117,Outlander,DIANA GABALDON,1996,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,1998,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,2002,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
126,Life of Pi,Yann Martel,2002,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
130,The Bean Trees,Barbara Kingsolver,1989,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,1995,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
135,ANGELA'S ASHES,Frank McCourt,1996,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
137,Good in Bed,Jennifer Weiner,2002,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,2002,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
140,American Gods,Neil Gaiman,2002,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
141,Skipping Christmas,JOHN GRISHAM,2001,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,1996,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,2002,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
157,The Color Purple,Alice Walker,1985,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
163,Silence of the Lambs,Thomas Harris,1991,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
166,About a Boy,Nick Hornby,1999,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,2001,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,1993,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,2003,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
182,Suzanne's Diary for Nicholas,James Patterson,2001,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
186,Lord of the Flies,William Gerald Golding,1959,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
192,A Prayer for Owen Meany,John Irving,1990,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,1986,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,2000,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

## Collabrative Filtering

In [26]:
#x[x].index is boolean indexing which is used to filter data
x=ratings_with_bookname.groupby('User-ID').count()['Book-Rating']>200
active_users = x[x].index
filtered_rating = ratings_with_bookname[ratings_with_bookname['User-ID'].isin(active_users)]
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [27]:
#A PivotTable is an interactive way to quickly summarize large amounts of data.
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')
pt.fillna(0,inplace=True)
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
similarity_scores = cosine_similarity(pt)
print(similarity_scores)
print(similarity_scores.shape)

[[1.         0.10255025 0.01220856 ... 0.12110367 0.07347567 0.04316046]
 [0.10255025 1.         0.2364573  ... 0.07446129 0.16773875 0.14263397]
 [0.01220856 0.2364573  1.         ... 0.04558758 0.04938579 0.10796119]
 ...
 [0.12110367 0.07446129 0.04558758 ... 1.         0.07085128 0.0196177 ]
 [0.07347567 0.16773875 0.04938579 ... 0.07085128 1.         0.10602962]
 [0.04316046 0.14263397 0.10796119 ... 0.0196177  0.10602962 1.        ]]
(706, 706)

In [30]:
# Enumerate allows you to keep track of the number of iterations (loops) in a loop.
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:11]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [31]:
recommend('You Belong To Me')

[['Loves Music, Loves to Dance',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671758896.01.MZZZZZZZ.jpg'],
 ["I'll Be Seeing You",
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671888587.01.MZZZZZZZ.jpg'],
 ['Before I Say Good-Bye',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671004573.01.MZZZZZZZ.jpg'],
 ["Daddy's Little Girl",
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0743206045.01.MZZZZZZZ.jpg'],
 ['All Around the Town',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671793489.01.MZZZZZZZ.jpg'],
 ['While My Pretty One Sleeps',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671673688.01.MZZZZZZZ.jpg'],
 ['My Gal Sunday',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0684832291.01.MZZZZZZZ.jpg'],
 ['Moonlight Becomes You',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671867113.01.MZZZZZZZ.jpg'],
 ['The Cradle Will Fall',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671741195.01.MZZZZZZZ.jpg'],
 ['Let Me Call You Sweetheart',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671568175.01.MZZZZZZZ.jpg']]